const tabelinha = {
            
  'adressesOfImg' :['./prodImgs/Quasar Classic Desodorante Colônia 125ml.webp',
'./prodImgs/Kit Presente Dia dos Pais Boticollection Portinari.webp',
'./prodImgs/Kit Presente Eudora Rouge: Eau de Parfum 35ml + Creme Corporal 100ml.jpg',
'./prodImgs/Presente Natura Biografia Masculino.jpg',
'./prodImgs/Creme Acetinado Lily Absolu 250g.webp',
'./prodImgs/Kit Presente Dia dos Pais Quasar.webp',
'./prodImgs/Celebre Sua Força Desodorante Colônia Feminino 100ml.webp',
'./prodImgs/Presente Natura Kaiak Masculino Completo.jpg',
'./prodImgs/Malbec Noir Desodorante Colônia 100ml.webp',
'./prodImgs/Kit Presente Dia dos Pais Uomini.jpg',
'./prodImgs/Presente Natura Essencial com Acessório.jpg',
'./prodImgs/Splash Desodorante Colônia The Blend Cardamom 200ml.webp',
'./prodImgs/Kit Presente Dia dos Pais Malbec.webp',
'./prodImgs/Quasar Rush Desodorante Colônia 100ml.webp',
'./prodImgs/Máscara Capilar Siàge Nutri Óleos Poderosos 250g.webp',
'./prodImgs/Kit Presente Nativa Spa Ameixa .webp',
'./prodImgs/Niina Secrets Desodorante Colônia 100ml.webp',
'./prodImgs/Egeo Hit Desodorante Colônia 90ml.webp',
'./prodImgs/Quasar Desodorante Colônia 100ml.webp',
'./prodImgs/Siàge Nutri Óleos Poderosos Shampoo.webp',
'./prodImgs/Siàge Nutri Óleos Poderosos Condicionador.jpeg',
'./prodImgs/Lily Absolu Eau de Parfum 75ml.webp',
'./prodImgs/Kit Siàge Nutri Óleos Poderosos.webp']
  ,
  'names' : ['Quasar Classic Desodorante Colônia 125ml',
'Kit Presente Dia dos Pais Boticollection Portinari',
'Kit Presente Eudora Rouge: Eau de Parfum 35ml + Creme Corporal 100ml',
'Presente Natura Biografia Masculino',
'Creme Acetinado Lily Absolu 250g',
'Kit Presente Dia dos Pais Quasar',
'Celebre Sua Força Desodorante Colônia Feminino 100ml',
'Presente Natura Kaiak Masculino Completo',
'Malbec Noir Desodorante Colônia 100ml',
'Kit Presente Dia dos Pais Uomini',
'Presente Natura Essencial com Acessório',
'Splash Desodorante Colônia The Blend Cardamom 200ml',
'Kit Presente Dia dos Pais Malbec',
'Quasar Rush Desodorante Colônia 100ml',
'Máscara Capilar Siàge Nutri Óleos Poderosos 250g',
'Kit Presente Nativa Spa Ameixa ',
'Niina Secrets Desodorante Colônia 100ml',
'Egeo Hit Desodorante Colônia 90ml',
'Quasar Desodorante Colônia 100ml',
'Siàge Nutri Óleos Poderosos Shampoo',
'Siàge Nutri Óleos Poderosos Condicionador',
'Lily Absolu Eau de Parfum 75ml',
'Kit Siàge Nutri Óleos Poderosos']
  ,
  'prices' : ['149.9',
'177.9',
'104.99',
'149.9',
'104.9',
'141.9',
'79.9',
'149.9',
'189.9',
'166.9',
'264.9',
'82.9',
'294.9',
'129.9',
'63.99',
'135.9',
'149.9',
'119.9',
'124.9',
'35.99',
'38.99',
'259.9',
'70.0']
};

export default tabelinha;
